name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-kind:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.issue.labels.*.name }}"
          echo "::error Please set either kind/feature, kind/improvement, kind/bug or skip-release-notes"
