name: Release candidate

on:
  push:
    branches:
      - start_it

jobs:
  rc:
    name: Trigger release candidate build
    runs-on: ubuntu-latest
    container: weaveworks/eksctl-build:5705efb32cdbf4531b282dba24dae03a872f5b31
    steps:
      - uses: actions/github-script@v3
        name: Wait for integration tests to pass
        id: it-status
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let tries = 0;
            async function checkStatus() {
              // There's no other way to identify the integration test job
              // GH branch protections are also just a string
              // must be in sync with integration-tests.yaml
              const integrationTestsCheckName = "Run integration tests";
              const { data } = await github.checks.listForRef({
                ...context.repo,
                ref: "${{ github.sha }}",
                check_name: integrationTestsCheckName,
              });
              return data.check_runs.some(cr =>
                cr.status === "completed" && cr.conclusion === "success"
              );
            }
            if (!(await checkStatus())) {
              await github.actions.createWorkflowDispatch({
                ...context.repo,
                ref: "${{ github.sha }}",
                workflow_id: "integration-tests.yaml",
              });
            }
            await new Promise((resolve, reject) => {
              let go = () => {
                if (tries > 10) {
                  reject("Timed out waiting for tests to complete");
                }
                tries = tries + 1;
                checkStatus().then(
                  success => success ? resolve("Tests completed successfully") : setTimeout(go, 6000)
                );
              }
              go();
             });
